### ISSUE TITLE
IDEs - Which do you use and what add-ons/tips/tricks to do you have?

### ISSUE THREAD

**Issue by ns-rse** [RSE-Sheffield/team-python#16]
Having a good IDE experience vastly improves your productivity as you can navigate code faster, auto-format and lint code on the fly, run tests in a more focused manner etc.  all of which shortens the feedback loop and in turn development time.

I thought it might be useful to have a discussion on what people use and perhaps show-case.

Obviously you should all be using [Emacs](https://www.gnu.org/software/emacs/), but I know [VSCode](https://code.visualstudio.com/) and [PyCharm](https://www.jetbrains.com/pycharm/) are popular and there are others like [Spyder](https://www.spyder-ide.org/).

Most are actually using the [Language Server Protocol](https://microsoft.github.io/language-server-protocol/) in the background but for Python there are, as with many other situations, lots of packages that do the same thing.

* [Pylsp](https://github.com/python-lsp/python-lsp-server)
* [Jedi Language Server](https://github.com/pappasam/jedi-language-server)
* [Palantair (deprecated)](https://github.com/palantir/python-language-server)
* [Pyright](https://emacs-lsp.github.io/lsp-pyright/)
* [Python (Microsoft)](https://emacs-lsp.github.io/lsp-python-ms)
* [Ruff](https://github.com/charliermarsh/ruff-lsp)

Which do people use? Why? Any Pros/Cons/niggles? How do you configure it?

There are also often additional add-ons that smooth the flow. For Emacs I use

* [pyvenv](https://github.com/jorgenschaefer/pyvenv) for switching between virtualenvs.
* [python-pytest](https://github.com/wbolster/emacs-python-pytest) for running tests.
* [blacken](https://github.com/pythonic-emacs/blacken) for `black`ening buffers.
* [flymake-ruff](https://github.com/erickgnavar/flymake-ruff) for `ruff`ling my files.
* [numpydoc](https://github.com/douglasdavis/numpydoc.el) for generating Numpy-style doc strings from `class/def`.
* [EIN](https://github.com/millejoh/emacs-ipython-notebook) for running iPython/Jupyter Notebooks in Emacs (Emacs Ipython Notebooks).

[TreeSitter](https://tree-sitter.github.io/tree-sitter/) is something I've started playing with recently too as at a bare minimum it gives consistent syntax highlighting, but can do so much more (e.g. [generate doc strings on the fly](https://mastodon.social/@spaceotter@mastodon.online/109671596235038019).

**Comment by Joe-Heffer-Shef** [comment]
I use PyCharm Professional edition using their free educational license:
[JetBrains Free Educational Licenses](https://www.jetbrains.com/community/education/#students)

Pros
* Excellent IDE with code navigation, project management, auto-complete, debugging, etc.
* Lots of plugins for other file types (markdown, bash, docker, etc.)
* Database integration (it can connect to SQL, NoSQL, etc.)

Cons
* High resource usage
* Complicated

I also rate VSCode and Notepad++ quite highly in general.

**Comment by bobturneruk** [comment]
I could talk about vscode.

**Comment by twinkarma** [comment]
Covered 15/04/2024
