### ISSUE TITLE
Can't add a card to the project board without adding an issue?

### ISSUE THREAD

**Issue by muneerahp** [RSE-Sheffield/team-python#3]

**Comment by muneerahp** [comment]
And....that was me testing.
From which it seems I can't add a card even if it is an issue. 
Google tells me there should be an Add Cards button, but assuming I'm not part of some group that allows that to be the case?

**Comment by Robadob** [comment]
I presume you will need to be added to the RSE-Sheffield Org  by @willfurnass or @mondus to have write privileges to any of the organisations repos.
